[package]
org = "hashithsithuruwan"
name = "central_service"
version = "0.1.0"
distribution = "2201.12.7"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "postgresql"
version = "1.16.1"

[[dependency]]
org = "ballerinax"
name = "kafka"
version = "4.6.0"