[package]
org = "hashithsithuruwan"
name = "green_proxy"
version = "0.1.0"
distribution = "2201.12.7"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "redis"
version = "3.0.0"
