[package]
org = "hashithsithuruwan"
name = "green_proxy"
version = "0.1.0"
distribution = "2201.12.7"

[build-options]
observabilityIncluded = true
cloud = "docker"

[[dependency]]
org = "ballerinax"
name = "redis"
version = "3.0.0"

[[dependency]]
org = "ballerinax"
name = "kafka"
version = "4.6.0"
