[package]
org = "hashithsithuruwan"
name = "visualization_service"
version = "0.1.0"
distribution = "2201.12.7"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerina"
name = "websocket"
version = "2.14.0"

[[dependency]]
org = "ballerinax"
name = "kafka"
version = "4.6.0"

[[dependency]]
org = "ballerina"
name = "http"
version = "2.12.0"

[[dependency]]
org = "ballerina"
name = "log"
version = "2.12.0"

[[dependency]]
org = "ballerina"
name = "time"
version = "2.7.0"

[[dependency]]
org = "ballerina"
name = "uuid"
version = "1.10.0"
